# Generated by Django 3.2.9 on 2021-12-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grades',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='answer',
            name='code',
            field=models.CharField(max_length=256),
        ),
    ]
