# Generated by Django 3.2.9 on 2021-11-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='ouput_description',
            new_name='output_description',
        ),
    ]
