# Generated by Django 3.2.9 on 2021-12-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='code',
            field=models.CharField(max_length=256),
        ),
    ]
