# Generated by Django 3.2.9 on 2021-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(blank=True, to='app.Student'),
        ),
    ]
