# Generated by Django 3.2.9 on 2021-12-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_answer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grades',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
